#!/usr/bin/env python3
"""Regenerate the thinTiny glyph sheet + C# glyph array from thinTiny_full.pixaki.

Iter-25 reproducibility tool. The COMMITTED source of truth is the generated
unity/ItemChecklist/Art/thinTiny_glyphs.png + the array baked into
ThinTinyGlyphPatch.cs — this script only re-derives them if the .pixaki changes.

Inputs:
  - sources/thinTiny_full.pixaki   (the master; layers Atlas + Rects + Dims + Background)
  - sources/glyph-templates/glyph_metrics.json  (thinSmall arrangement, from the runtime dump)
Outputs:
  - unity/ItemChecklist/Art/thinTiny_glyphs.png   (the Atlas layer, the sprite sheet)
  - prints the C# Glyphs[,] rows to paste into ThinTinyGlyphPatch.cs

How it works: each new glyph (drawn in the .pixaki, missing from thinTiny) is placed at
its thinSmall cell (col = x//8, row from top), the Rects layer gives its advance width,
and the sprite rect is in the Atlas layer. Sprite rects are emitted in Unity coords
(origin bottom-left). The runtime then replicates PugFont.InitCodePoints' rect2+pivot.

NOTE: glyph_metrics.json is gitignored (Pugstorm-derived) and is regenerated by
dump_log_to_json.py from a Player.log diagnostic dump (see that script's header).
"""
import json, zipfile, os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PIXAKI = os.path.join(REPO, "sources", "thinTiny_full.pixaki")
METRICS = os.path.join(HERE, "glyph_metrics.json")
SHEET = os.path.join(REPO, "unity", "ItemChecklist", "Art", "thinTiny_glyphs.png")
NEWCDX, NEWCDY = 8, 10

def layer_full(zf, sp, cels, W, H, name):
    L = next(l for l in sp["layers"] if l.get("name") == name)
    cel = cels[L["clips"][0]["itemIdentifier"]]; (fx, fy), _ = cel["frame"]
    full = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    full.alpha_composite(Image.open(zf.open(f"images/drawings/{cel['identifier']}.png")).convert("RGBA"), (fx, fy))
    return full

def mbbox(img, cx, cy):
    cell = img.crop((cx, cy, cx + NEWCDX, cy + NEWCDY)); px = cell.load(); xs = []; ys = []
    for yy in range(NEWCDY):
        for xx in range(NEWCDX):
            r, g, b, a = px[xx, yy]
            if a > 0 and r > 140 and b > 140 and g < 130: xs.append(xx); ys.append(yy)
    return (cx + min(xs), cy + min(ys), max(xs) - min(xs) + 1, max(ys) - min(ys) + 1) if xs else None

def main():
    if not os.path.exists(METRICS):
        sys.exit(f"glyph_metrics.json missing ({METRICS}) — regenerate it via dump_log_to_json.py first")
    zf = zipfile.ZipFile(PIXAKI); d = json.load(zf.open("document.json")); sp = d["sprites"][0]; W, H = sp["size"]
    cels = {c["identifier"]: c for c in sp["cels"]}
    atlas = layer_full(zf, sp, cels, W, H, "Atlas")
    rects = layer_full(zf, sp, cels, W, H, "Rects")
    gm = json.load(open(METRICS)); ss = gm["fonts"]["thinSmall"]
    ss_cdy = ss["charDims"][1]; ss_rows = ss["atlas"][1] // ss_cdy; tt_cp = gm["fonts"]["thinTiny"]["codePoints"]
    glyphs = []
    for g in ss["glyphs"]:
        for code in g["chars"]:
            if str(code) in tt_cp: continue
            x, y, w, h = g["rect"]; col = x // 8; row = (ss_rows - 1) - (y // ss_cdy)
            cx, cy = col * NEWCDX, row * NEWCDY
            if cx + NEWCDX > W or cy + NEWCDY > H: continue
            rb = mbbox(rects, cx, cy)
            if rb: glyphs.append((code, rb))
    glyphs.sort()
    atlas.save(SHEET)
    print(f"// wrote {SHEET} ({W}x{H}), {len(glyphs)} glyphs")
    print("// paste into ThinTinyGlyphPatch.cs Glyphs[,]  { code, x, y(unity), w, h }")
    for code, (rx, ry, rw, rh) in glyphs:
        print(f"            {{ {code}, {rx}, {H - (ry + rh)}, {rw}, {rh} }},")

if __name__ == "__main__":
    main()
